baseurl: ""
url: "https://gleam.run/"

markdown: kramdown

permalink: "/news/:title/"

title: Gleam
description: Gleam is a fast, friendly, and functional language for building type-safe, scalable systems!

plugins:
  - jekyll-redirect-from
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-feed

exclude:
  - README
  - Makefile
  - book-src

include:
  - .well-known

defaults:
  -
    scope:
      path: ""      # all files
      type: posts   # limit to posts
    values:
      layout: post

# Syntax highlighting is handled by highlight.js
highlighter: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
