[book]
authors = ["Louis Pilfold"]
multilingual = false
src = "book-src"
title = "The Gleam Book"

[output.html]
additional-js = ["javascript/highlightjs-gleam.js", "javascript/plausible.js"]
git-repository-url = "https://github.com/gleam-lang/website"
git-repository-icon = "fa-github"

[output.html.redirect]
"tour/type-annotations" = "./let-bindings.html"
"tour/type-annotations.html" = "./let-bindings.html"
