name = "website"
version = "1.0.0"
gleam = ">= 1.9.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
gleam_time = ">= 1.1.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
filepath = ">= 1.1.1 and < 2.0.0"
contour = ">= 1.1.1 and < 2.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
gleave = ">= 1.0.0 and < 2.0.0"
snag = ">= 1.1.0 and < 2.0.0"
jot = ">= 7.0.0 and < 8.0.0"
atomb = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
just = ">= 2.0.0 and < 3.0.0"
pearl = ">= 2.1.0 and < 3.0.0"
tear = ">= 1.0.0 and < 2.0.0"
houdini = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
